### ISSUE TITLE
Charm++ 8.0.0 distribution missing from Charm website

### ISSUE THREAD

**Issue by RMeli** [charmplusplus/charm#3827]
I'd like to add the latest version of Charm++ to Spack, but as far as I can tell it is missing from [https://charm.cs.illinois.edu/distrib/](https://charm.cs.illinois.edu/distrib/), which is what Spack currently uses.

Will the new version be added there, or from now on it is only distributed via GitHub/other means?

**Comment by lvkale** [comment]
Apologies for the slow response. We were hoping to have done with a transition to a new server for this website, which has somehow been delayed. We could put it at charmplusplus.org.  But will it work for spack if it is github alone?

**Comment by ericjbohm** [comment]
I have placed the charm-8.0.0.tar.gz file in this directory on the web server.

**Comment by RMeli** [comment]
Thank you both!

> We could put it at charmplusplus.org. But will it work for spack if it is github alone?

Spack can indeed work with GitHub (although apparently the hash of the package can sometime change), and [I used the GitHub archive as a one-off solution](https://github.com/spack/spack/blob/b3d82dc3a8fda9344f47e395accaeaf4bffbd561/var/spack/repos/builtin/packages/charmpp/package.py#L29-L33).

I was wondering if this was only an one-off/oversight or if something changed in the way you distribute the source code (which will require a more permanent solution on the Spack package).

> I have placed the charm-8.0.0.tar.gz file in this directory on the web server.

Thanks @ericjbohm, I will revert this is Spack the next time I touch the package.
