### ISSUE TITLE
Molecular2D example doesn't compile

### ISSUE THREAD

**Issue by ritvikrao** [charmplusplus/charm#3834]
In examples/charm++/Molecular2D, which includes entry methods which take CkVec objects as parameters, when attempting to compile, the following error is thrown:

```
In file included from Patch.C:403:
./Patch.def.h:765:26: error: non-const lvalue reference to type 'CkVec<...>' cannot bind to a temporary of type 'CkVec<...>'
  impl_obj->updateForces(std::move(particles.t));
```

**Comment by mayantaylor** [comment]
PR #2886 might be relevant

**Comment by stwhite91** [comment]
How was this unnoticed for so long? Is Molecular2d not compiled by default as part of "make test"? If not, it should probably be added to that...

**Comment by ritvikrao** [comment]
Make test only compiles the tests, right? This is in the examples folder. Should examples also be added to the list of tests?

**Comment by ericjbohm** [comment]
The examples/charm++/Makefile only operates on a specific enumerated list
of directories and Molecular2d is not in that list.
