### ISSUE TITLE
Is the "basedir" a prefix?

### ISSUE THREAD

**Issue by VictorEijkhout** [charmplusplus/charm#3849]
I build
```
./build charm++ ucx-linux-arm8 --build-shared --basedir=$(pwd)/../installation-old --force
```
but the basedir seems to be ignored: the lib directory is under ucx-linux-arm8.

**Comment by ZwFink** [comment]
You should use ` --install-prefix=` instead

**Comment by VictorEijkhout** [comment]
Thanks. I didn't see that in the documentation.
